services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
    ports: 
      - "9001:1433"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_USER: postgres
    ports:
      - "9002:5432"
